# Generated by Django 2.0 on 2018-12-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('desc', models.TextField(verbose_name='简介')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('occupation', models.CharField(default='学生', max_length=20, verbose_name='职业')),
                ('company', models.CharField(default='', max_length=20, verbose_name='公司')),
            ],
            options={
                'verbose_name': '我的信息',
                'verbose_name_plural': '我的信息',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='技能')),
                ('master_rate', models.IntegerField(verbose_name='技能掌握比')),
            ],
            options={
                'verbose_name': '技能掌握',
                'verbose_name_plural': '技能掌握',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Skill', verbose_name='技能'),
        ),
    ]
