# Generated by Django 2.0 on 2018-12-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default='', max_length=20, verbose_name='链接'),
        ),
    ]
