# Generated by Django 2.0 on 2018-12-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='注意事项')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '注意事项',
                'verbose_name_plural': '注意事项',
            },
        ),
    ]
