# Generated by Django 2.0 on 2019-01-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_notice_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
