# Generated by Django 2.0 on 2018-12-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_category_link'),
        ('Blog', '0002_auto_20181219_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Category.Category', verbose_name='博客类型'),
        ),
    ]
