# Generated by Django 2.0 on 2018-12-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数量'),
        ),
    ]
