# Generated by Django 2.0 on 2018-12-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/', verbose_name='博客图片'),
        ),
    ]
