# Generated by Django 2.0 on 2018-12-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20181219_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='introduction',
            field=models.TextField(default='', verbose_name='前言'),
        ),
    ]
