# Generated by Django 2.0 on 2018-12-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20181219_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
    ]
