# Generated by Django 2.0 on 2018-12-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20181225_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
