# Generated by Django 2.0 on 2019-01-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20181225_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='轮播顺序')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='图片')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Blog', verbose_name='轮播博客')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
