# Generated by Django 2.0 on 2019-01-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='share_times',
            field=models.IntegerField(default=0, verbose_name='分享次数'),
        ),
    ]
