# Generated by Django 2.0 on 2019-01-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': '友链', 'verbose_name_plural': '友链'},
        ),
        migrations.AlterField(
            model_name='links',
            name='add_time',
            field=models.DateField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
