# Generated by Django 2.0 on 2018-12-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_emailverifyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=200, verbose_name='名言')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
            ],
            options={
                'verbose_name': '名言',
                'verbose_name_plural': '名言',
            },
        ),
    ]
