# Generated by Django 2.0 on 2018-12-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
