# Generated by Django 2.0 on 2018-12-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_auto_20181219_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_to_who',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='root',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
